### ISSUE TITLE
Default export doesn't work with ESM modules

### ISSUE THREAD

**Issue by jamesmoss** [deptyped/prisma-extension-pagination#20]
We're using ESM modules in Node v18, the default export isn't working properly so it's not possible to import the extension correctly and use it. Using the example at the top of the readme gives the error "pagination is not a function".

I've recreated the issue here https://codesandbox.io/p/devbox/recursing-swartz-zyffh8?file=%2Findex.mjs%3A5%2C1

The named exports are working fine, if we can add the extension as a named export that would solve the issue.

**Comment by deptyped** [comment]
Named export for extension available since 0.6.0. Thanks for the bug report!
