### ISSUE TITLE
Prisma `5.13.0` introduce `omit` but not working with `prisma-extension-pagination`

### ISSUE THREAD

**Issue by mamlzy** [deptyped/prisma-extension-pagination#32]
Here is my code:

_// schema.prisma_
![image](https://github.com/deptyped/prisma-extension-pagination/assets/63343105/a77303e3-5be3-4efb-bc60-9c42ad0dba65)

_// api_
![image](https://github.com/deptyped/prisma-extension-pagination/assets/63343105/ad9aaf47-95b0-4458-89aa-94dde20b66d6)

Here is the erorr message on my terminal:

![image](https://github.com/deptyped/prisma-extension-pagination/assets/63343105/4480f382-f5b3-4e2c-afb7-4a95415fdaa5)

**Comment by deptyped** [comment]
Thanks for reporting, should be fixed in 0.7.3
