### ISSUE TITLE
ESM error at build time "SyntaxError: Named export 'paginate' not found."

### ISSUE THREAD

**Issue by SahidMiller** [deptyped/prisma-extension-pagination#6]
Hi, I'm running into the following error after building this package

```
import { paginate } from "prisma-extension-pagination";

SyntaxError: Named export 'paginate' not found. The requested module 'prisma-extension-pagination' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

Fixing this error using default exports generates TS errors. 

I believe this is caused by the package.json not having a `type: "module"` or not having microbundle emit with .mjs extension.

Removing `"module": "/dist/index.mjs"` and then running `npm run build` emits `/dist/index.esm.mjs`.

**Comment by deptyped** [comment]
@SahidMiller Can you test version 0.2.4? Should be fixed now

**Comment by SahidMiller** [comment]
Seems to be working great on my end. Thank you, @deptyped.

**Comment by deptyped** [comment]
@SahidMiller thank you for your contribution! I will close this issue. Feel free to open it if you discover any problems.
