### ISSUE TITLE
Export total count

### ISSUE THREAD

**Issue by dolev-edgify** [deptyped/prisma-extension-pagination#8]
Hi!

Can you export the total count as part of PageNumberPaginationMeta?

There's a working implementation for that in Sahid Miller's fork - here: 
https://github.com/SahidMiller/prisma-extension-pagination/tree/feat/total-counts - I believe you can just merge it with main...

Thanks!

**Comment by deptyped** [comment]
Thanks for suggestion! Added in 0.3.0

**Comment by deptyped** [comment]
Thanks for suggestion! Added in 0.3.1

**Comment by dolev-edgify** [comment]
Thanks!
